# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fiASSB26MHNhRgDcOKqxaVIdx4wz4_eJ
"""

print("hello world")